export const FETCH_PROFILE_REQUEST = "FETCH_PROFILE_REQUEST";
export const FETCH_PROFILE_SUCCESS = "FETCH_PROFILE_SUCCESS";
export const FETCH_RESET_PASS_SUCCESS = "FETCH_RESET_PASS_SUCCESS";
export const FETCH_PROFILE_FAILURE = "FETCH_PROFILE_FAILURE";
export const FETCH_GENERATE_CODE_SUCCESS = "FETCH_GENERATE_CODE_SUCCESS";
export const FETCH_EDIT_EMAIL_SUCCESS = "FETCH_EDIT_EMAIL_SUCCESS";